export const CLASSES = [
  {
    id: 'warrior',
    name: 'Warrior',
    tag: 'Melee Juggernaut',
    desc: 'High life and armor. Cleaves enemies apart in melee range.',
    color: '#a13328',
    startSkill: 'slash',
    base: { maxHp: 150, speed: 175, armor: 6, hpRegen: 0, critChance: 0.05, critMult: 1.5 },
  },
  {
    id: 'sorceress',
    name: 'Sorceress',
    tag: 'Elemental Caster',
    desc: 'Fragile but devastating. Hurls fireballs from a distance.',
    color: '#6b4a8a',
    startSkill: 'fireball',
    base: { maxHp: 95, speed: 165, armor: 0, hpRegen: 0, critChance: 0.08, critMult: 1.6 },
  },
  {
    id: 'ranger',
    name: 'Ranger',
    tag: 'Swift Marksman',
    desc: 'Fast and evasive. Fires rapid shots while kiting the horde.',
    color: '#5c7a3d',
    startSkill: 'quickshot',
    base: { maxHp: 115, speed: 195, armor: 2, hpRegen: 0, critChance: 0.1, critMult: 1.5 },
  },
  {
    id: 'skeleton',
    name: 'The Skeleton',
    tag: 'Risen Bonecaster',
    desc: 'Tireless and unliving. Hurls bones that ricochet between the horde.',
    color: '#a89e85',
    startSkill: 'bonethrow',
    base: { maxHp: 120, speed: 178, armor: 3, hpRegen: 0, critChance: 0.06, critMult: 1.5 },
  },
  {
    id: 'plaguedoctor',
    name: 'Plague Doctor',
    tag: 'Harvester of the Sick',
    desc: 'Reaps the horde with a wide scythe, sweeping everything in front of him.',
    color: '#5f7a4a',
    startSkill: 'scythe',
    base: { maxHp: 125, speed: 172, armor: 4, hpRegen: 0.4, critChance: 0.06, critMult: 1.55 },
  },
  {
    id: 'shinobi',
    name: 'Shinobi',
    tag: 'Silent Blade',
    desc: 'Lightning quick and lightly armored. Orbits a whirling ring of ninja stars.',
    color: '#4a5a72',
    startSkill: 'ninjastars',
    base: { maxHp: 100, speed: 210, armor: 1, hpRegen: 0, critChance: 0.12, critMult: 1.7 },
  },
];
